name: Deploy
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to target system
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.DIMENSION_DEPLOYMENT_USER }}
          key: ${{ secrets.DIMENSION_DEPLOYMENT_SSH_KEY }}
          port: 22
          script: |
            cd /srv/wiki
            sudo git config pull.ff only
            sudo git reset --hard
            sudo git pull
