name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to target
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.DIMENSION_DEPLOYMENT_USER }}
          key: ${{ secrets.DIMENSION_DEPLOYMENT_SSH_KEY }}
          port: 22
          script: |
            cd /srv/wiki/
            sudo git pull